const fileName = [
  {
    src: "the-fool.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-magician.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-high-priestess.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-empress.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-emperor.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-hierophant.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-lovers.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-chariot.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "strength.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-hermit.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-wheel-of-fortune.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "justice.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-hanged-man.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "death.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "temperance.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-devil.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-tower.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-star.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-moon.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-sun.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "judgement.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "the-world.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "ace-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "2-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "3-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "4-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "5-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "6-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "7-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "8-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "9-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "10-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "page-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "knight-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "queen-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "king-of-cups.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },

  {
    src: "ace-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "2-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "3-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "4-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "5-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "6-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "7-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "8-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "9-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "10-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "page-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "knight-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "queen-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "king-of-pentacles.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "ace-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "2-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "3-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "4-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "5-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "6-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "7-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "8-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "9-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "10-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "page-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "knight-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "queen-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "king-of-swords.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "ace-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "2-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "3-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "4-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "5-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "6-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "7-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "8-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "9-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "10-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "page-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "knight-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "queen-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
  {
    src: "king-of-wands.jpg",
    mean: {
      overview: "",
      work: "",
      love: "",
      finance: "",
      spirit: "",
      health: "",
    },
  },
];

const backTarotName = [
  { src: "behind1.jpg" },
  { src: "behind2.jpg" },
  { src: "behind3.jpg" },
  { src: "behind4.jpg" },
  { src: "behind5.jpg" },
  { src: "behind6.jpg" },
  { src: "behind7.jpg" },
  { src: "behind8.jpg" },
  { src: "behind9.jpg" },
  { src: "behind10.jpg" },
];

const stoneName = [
  { src: "stone1.png" },
  { src: "stone1.png" },
  { src: "stone2.png" },
  { src: "stone3.png" },
  { src: "stone4.png" },
  { src: "stone5.png" },
  { src: "stone6.png" },
  { src: "stone7.png" },
  { src: "stone8.png" },
  { src: "stone9.png" },
  { src: "stone10.png" },
];

export { fileName, backTarotName, stoneName };
